#!/usr/bin/env python3
"""Embed compact licensed source tiles so captures work from any directory."""
from pathlib import Path
root=Path(__file__).resolve().parent.parent
out=root/'src/object_materials.generated.h'
parts=['// Generated by tools/embed-materials.py. Do not edit.\n#pragma once\n']
for name in ('wood','metal','fabric'):
    data=(root/'assets/materials'/f'{name}.jpg').read_bytes()
    parts.append(f'static const unsigned char object_{name}[] = {{\n')
    parts.extend(','.join(str(b) for b in data[i:i+24])+',\n' for i in range(0,len(data),24))
    parts.append('};\n')
text=''.join(parts)
if not out.exists() or out.read_text()!=text: out.write_text(text)
