#!/usr/bin/env python3
"""Embed licensed assets so the executable works from any directory."""
import argparse
from pathlib import Path

root = Path(__file__).resolve().parent.parent
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('group', nargs='?', choices=('objects', 'models'))
args = parser.parse_args()
groups = {
    'objects': ('object_materials.generated.h', [
        (f'object_{name}', root/'assets/materials'/f'{name}.jpg')
        for name in ('wood', 'metal', 'fabric')]),
    'models': ('models.generated.h', [
        ('model_'+str(i), path) for i, path in enumerate(sorted((root/'assets/models').rglob('*.glb')))]),
}
for group in ([args.group] if args.group else groups):
    filename, assets = groups[group]
    parts = ['// Generated by tools/embed-materials.py. Do not edit.\n#pragma once\n']
    for symbol, path in assets:
        data = path.read_bytes()
        parts.append(f'static const unsigned char {symbol}[] = {{\n')
        parts.extend(','.join(str(b) for b in data[i:i+24])+',\n'
                     for i in range(0, len(data), 24))
        parts.append('};\n')
    if group == 'models':
        parts.append('static const EmbeddedAsset modelAssets[] = {\n')
        for symbol, path in assets:
            key=path.relative_to(root/'assets').as_posix()
            parts.append(f'{{"{key}",{symbol},sizeof({symbol})}},\n')
        parts.append('};\n')
    out = root/'src'/filename
    text = ''.join(parts)
    if not out.exists() or out.read_text() != text:
        out.write_text(text)
    else:
        out.touch()  # Satisfy make after an input changes without changing bytes.
