#!/usr/bin/env python3
"""Embed licensed assets so the executable works from any directory."""
import argparse
from pathlib import Path

root = Path(__file__).resolve().parent.parent
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('group', nargs='?', choices=('objects', 'revolver'))
args = parser.parse_args()
groups = {
    'objects': ('object_materials.generated.h', [
        (f'object_{name}', root/'assets/materials'/f'{name}.jpg')
        for name in ('wood', 'metal', 'fabric')]),
    'revolver': ('revolver.generated.h', [
        ('revolver_'+name.split('.')[0].replace('-', '_'), root/'assets/revolver'/name)
        for name in ('mesh.bin', 'poses.bin', 'gun.jpg', 'ammo.jpg',
                     'gun-detail.png', 'ammo-detail.png')]),
}
for group in ([args.group] if args.group else groups):
    filename, assets = groups[group]
    parts = ['// Generated by tools/embed-materials.py. Do not edit.\n#pragma once\n']
    for symbol, path in assets:
        data = path.read_bytes()
        parts.append(f'static const unsigned char {symbol}[] = {{\n')
        parts.extend(','.join(str(b) for b in data[i:i+24])+',\n'
                     for i in range(0, len(data), 24))
        parts.append('};\n')
    out = root/'src'/filename
    text = ''.join(parts)
    if not out.exists() or out.read_text() != text:
        out.write_text(text)
    else:
        out.touch()  # Satisfy make after an input changes without changing bytes.
